### ISSUE TITLE
InputfieldOpeningHours: A value was not a valid time string so it was deleted

### ISSUE THREAD

**Issue by ShadowMoses36** [juergenweb/FieldtypeOpeningHours#5]
Hi @juergenweb 

Firstly thanks for this plugin, its very helpful!

For some reason today I'm getting this error:

`InputfieldOpeningHours: A value was not a valid time string so it was deleted`

I've not made any changes to the times and they were fine yesterday. As far as I can see they're valid times.

Not sure what the problem is

Thanks
![Screenshot from 2022-05-01 16-29-46](https://user-images.githubusercontent.com/104727422/166152959-a3bad99c-ef0f-4212-9652-6dc7b36abb1b.png)

**Comment by juergenweb** [comment]
Hello ShadowMoses36

The times on your image are correct. Did you have entered an invalid time on Sunday or Holiday.  This is the code responsible for the message:

`// 2) Set inputs as a string and check if it is in a valid time format(H:i) - otherwise get rid of them
        $cleanedValues = [];
        foreach ($timeInputs as $key=>$value) {
            $value = strval($value);
            if ($value) {
                //check if value has valid time format (fe 08:00)
                if (OpeningHours::isTimeValid($value)) {
                    $cleanedValues[$key] = $value;
                } else {
                    $cleanedValues[$key] = '';
                    $this->error($this->_('A value was not a valid time string so it was deleted.'));
                }
            } else {
                //empty value
                $cleanedValues[$key] = '';
            }
        }`

So if there was an invalid time inside an inputfield, it will be deleted and not more visible. The input values above are all visible and therefore not responsible for this error message.
I dont know, where it comes from, but if your times are saved correctly please ignore this error message. 

Best regards

**Comment by pixelsenseuk** [comment]
@juergenweb thank you for the response, I will take a further look into the error this evening. It's a strange one, as it was okay the day before and I made a lot of edits to that page and others.

Perhaps it's conflicting with something else? I'll update you if I find a solution or the cause, for future reference.

Thank you
